In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('datasets/movies.csv')
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [3]:
df.dtypes

movieId    int64
title        str
genres       str
dtype: object

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10329 entries, 0 to 10328
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  10329 non-null  int64
 1   title    10329 non-null  str
 2   genres   10329 non-null  str
dtypes: int64(1), str(2)
memory usage: 242.2 KB

In [5]:
df.describe()

             movieId
count   10329.000000
mean    31924.282893
std     37734.741149
min         1.000000
25%      3240.000000
50%      7088.000000
75%     59900.000000
max    149532.000000

In [6]:
df.isna().any().any()

np.False_